#!/bin/bash
#Argument Read
#Script to make sure user input is provided

if [ -z $1 ]
then
	echo Provide Filenames
	read -p "Enter file name:" FILENAME 
else
	FILENAME="$@"
fi
echo the following filenames have been provided: $FILENAME
