#!/bin/bash
BLAH=rabarabarabarabarara

echo BLAH is $BLAH

echo 'The Result of ##*ba is ' ${BLAH##*ba}
echo 'The Result of #*ba is '  ${BLAH#*ba}
echo 'The Result of %%ba* is ' ${BLAH%%ba*}
echo 'The Result of %ba* is '  ${BLAH%ba*}
