#!/bin/bash
#Show the use of the shift

echo "The Argument provided are $*"
echo "The value of \$1 is $1"
echo "The entire string is $*"
shift
echo "The value of \$1 is $1"
echo "The entire string is $*"
exit

