#!/bin/bash
#Menu for sys admins

echo "Select a task"

select TASK in "Check Mount" "Check disk space" "Check Memory usage"
do
	case $REPLY in
		1)TASK=mount;;
		2)TASK="df -h";;
		3)TASK="free -m";;
		*)echo ERROR && exit 2;;
	esac
	if [ -n "$TASK" ]
	then
#		clear
		$TASK
		break
	else
		echo "Invalid choice" && exit3
	fi
done
